# Generated by Django 3.0.5 on 2020-05-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HouseHold',
            fields=[
                ('managerName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('postalCode', models.CharField(max_length=100)),
                ('products', models.ManyToManyField(through='foyer_france.Command', to='foyer_france.Product')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='houseHold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foyer_france.HouseHold'),
        ),
        migrations.AddField(
            model_name='command',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foyer_france.Product'),
        ),
    ]
