# Generated by Django 3.0.5 on 2020-05-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foyer_france', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='totalMembers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
