# Generated by Django 3.0.5 on 2020-05-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foyer_france', '0002_auto_20200503_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
