# Generated by Django 3.0.5 on 2020-05-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foyer_france', '0003_command_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='dateOfCommand',
            field=models.DecimalField(decimal_places=10, default=1588695363.9744973, max_digits=20),
        ),
    ]
